03-OutputParser/02-CommaSeparatedListOutputParser.ipynb
[Team] Existing content development team 2
[Title] Comma Separated List Output Parser
[Language] ENG
[Packages] langchain_core, lanchain_openai
Tutorial for Comma Separated List Output Parser and Simple Usage Examples
=> CommaSeparatedList OutputParser

docs/README.md
[Gitbook] Setup gitbook configuration
=> [Gitbook] Setup gitbook configuration

docs/03-OutputParser/02-CommaSeparatedListOutputParser.md
[Gitbook] 03-OutputParser Comma Separated List Output Parser
=> [Gitbook] 03-OutputParser Comma Separated List Output Parser

docs/03-OutputParser/02-CommaSeparatedListOutputParser.md
add custom style on markdown file
=> [Gitbook] 03-OutputParser 02-CommaSeparatedListOutputParse

05-MEMORY/01-ConversationBufferMemory.ipynb
[Title] Added `ConversationBufferMemory`
[Version] initial 
[Language] ENG 
[Package] langchain, langchain-openai
- Introduced a new Jupyter notebook for the `ConversationBufferMemory` class, detailing its usage for storing and retrieving conversation history.
- Included sections on environment setup, message extraction, and integration with `ConversationChain`.
=> [E-4] 05-MEMORY / 01-ConversationBufferMemory

06-DocumentLoader/08-TXT-Loader.ipynb, 06-DocumentLoader/data/appendix-keywords-CP949.txt, 06-DocumentLoader/data/appendix-keywords-EUCKR.txt, 06-DocumentLoader/data/appendix-keywords-utf8.txt, 06-DocumentLoader/data/appendix-keywords.txt
[Title] TXT Loader
[Language] ENG
[Package] langchain, langchain_community
LangChain TextLoader Tutorial
- Implemented text file loading using `TextLoader`.
- Demonstrated metadata extraction and content preview for individual text files.
- Showcased automatic encoding detection and error handling with DirectoryLoader.
=> [N-1] 06-DocumentLoader / 08-TXT-Loader

05-MEMORY/05-ConversationKGMemory.ipynb
[Title] ConversationKGMemory
[Language] ENG
[Package] langchain, langchain-community, langchain-openai
ConversationKGMemory Tutorial Implementation
- Introducing ConversationKGMemory to manage conversation entities and relationships in graph structure
- Demonstrated key features: save_context, get_current_entities, get_knowledge_triplets, load_memory_variables
- Showed practical example with a conversation scenario about a new employee
- Provided integration example with ConversationChain
=> [E-4] 05-MEMORY / 05-ConversationKGMemory

02-PROMPT/01-PromptTemplate.ipynb, 02-PROMPT/prompts/capital.yaml, 02-PROMPT/prompts/fruit_color.yaml
[Team] Existing Content Development Team 1
[Title] Prompt Template
[Language] ENG
[Packages] langchain_core.prompts, langchain_openai
LangChain PromptTemplate Tutorial
- Creating PromptTemplate objects.
- Loading prompt templates from YAML files.
- Utilizing ChatPromptTemplate and MessagePlaceholder.
=> [E-1] 02-PROMPT / 01-Prompt Template

04-MODEL/03-ModelSerialization.ipynb
[Title] Model Serialization
[Language] ENG
[Package] langchain_core, langchain-openai, pickle
LangChain Serialization tutorial
Describe what is serialization and some examples using load.dumps, load.loads, load.dumpd and load.load.
And how to serialize to or deserialize from pickle file.
=> [E3] 04-MODEL / 03-ModelSerialization

04-MODEL/07-HuggingFaceLocal.ipynb
[Title] HuggingFace Local
[Language] ENG
[Package] langchain, langchain_huggingface
LangChain HuggingFace Local Tutorial
- HuggingFace Local Model Setup and Usage
=> [E-3] 04-MODEL / 07-HuggingFace Local

08-EMBEDDING/04-UpstageEmbeddings.ipynb
처음이라 많이 부족합니다. 피드백 감사히 받겠습니다. 
다들 고생많으십니다!
=> [N-3] 08-Embedding / 04-UpstageEmbeddings

07-TextSplitter/02-RecursiveCharacterTextSplitter.ipynb
[Team] 신규2팀
[Title] 02-RecursiveCharacterTextSplitter
[Language] ENG
[Packages] langchain_text_splitters
=> [N-2] 07-Text Splitter / 02-RecursiveCharacterTextSplitter

07-TextSplitter/04-SemanticChunker.ipynb
[Title] SemanticChunker
[Version] bug fix
[Language] ENG
[Package] langsmith,langchain,langchain_core,langchain-anthropic,langchain_community,langchain_text_splitters,langchain_openai,langchain_experimental
=> [N-2] 07-Text Splitter / 04-SemanticChunker

06-DocumentLoader/10-Arxiv-loader.ipynb, 06-DocumentLoader/11-ArxivLoader.ipynb
[Team] New Content Development Team1
[Title] Arxiv Loader
[Language] ENG
[Packages] langchain-community, arxiv, pymupdf
Implemented Arxiv Loader refer the Arxiv API & Arxiv Loader in LangChain API
=> [N-1] 06-Document Loader / 11-ArxivLoader

08-EMBEDDING/02-CacheBackedEmbeddings.ipynb, 08-EMBEDDING/data/state_of_the_union.txt
[Title] CacheBackedEmbeddings
[Language] ENG
[Packages] langchain_openai, langchain_community, faiss
Added CacheBackedEmbeddings Notebook
=> [Team] New Content Development Team 3

03-OutputParser/02-CommaSeparatedListOutputParser.ipynb
이미 검토 완료되었던 내용 입니다. MR 과정에서 파일이 삭제되어 다시 올립니다.
=> [E-2] 03-OutputParser / 02-CommaSeparatedListOutputParser

07-TextSplitter/01-CharacterTextSplitter.ipynb
[N-2] 07-Text Splitter / 01-CharacterTextSplitter
=> [N-2] 07-Text Splitter / 01-CharacterTextSplitter

02-PROMPT/03-LangChain Hub.ipynb
[Team] Existing Content Development Team 1
[Title] 03-LangChain Hub
[Language] ENG
[Packages] langchain_core.prompts, langchain_openai
LangChain PromptTemplate Tutorial
=> 03-LangChain Hub.ipynb

CODE_OF_CONDUCT.md, LICENCE.txt, README.md
안녕하세요 @fastjw님,
상의하였던 랭체인 커뮤니티 인증을 위한 기본 문서들과 리드미 수정 (초안) 입니다. 라이센스 등 확정 사항에 따라 이후 수정 가능합니다.
감사합니다.
=> [Docs] draft license / code-of-conduct / readme

CODE_OF_CONDUCT.md, LICENCE.txt, README.md
@teddylee777님,
수고 많으십니다. https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/pull/135 업데이트 버전입니다. Contribution Process 부분은 가장 최근 팀 미팅 공지사항을 반영하고 번역/검수팀에서 요청할 추가 내용과 함께 확정되는대로 수정하겠습니다.
감사합니다.
=> [Docs] update license / code-of-conduct / readme

README.md
Remove Team Dashboard link on README.md
Add 1/4 Team Note
=> [REAMDE.md Update] Quick Fix on README.md

08-Embedding/03-HuggingFaceEmbeddings.ipynb
- !pip -> %pip로 변경
- italics를 bold 또는 backtic으로 교체
- 백틱 뒤에는 한칸 띄어쓰기 반영
- 문맥의 통일성 반영(embedded_document로 수정)
```markdown
```
=> [N-3] 08-Embedding / 03-HuggingFaceEmbeddings

13-LangChain-Expression-Language/09-Generator.ipynb
- 기존 wiki 자료 번역 진행
- RunnableGenerator 내용 신규 추가
```markdown
```
=> [E-4] 13-LangChain-Expression-Language / 09-Generator

08-Embedding/01-OpenAIEmbeddings.ipynb
1. Escape 문자 포함
2. 한글 -> 영문  수정
3. 영문 번역 반영
꼼꼼히 체크 해주셔서 감사합니다.
Reviewers로 다른 한분을 어떤 분으로 해야할지 모르겠어서 같은 주제로 pr하신 #170  참고하였는데
BokyungisaGod님으로 하면 될까요~?
```markdown
```
=> [N-3] 08-Embedding / 01-OpenAIEmbeddings.ipynb

13-LangChain-Expression-Language/07-ChainDecorator.ipynb
=> [E-4] 13-LangChain-Expression-Language / 07-ChainDecorator

13-LangChain-Expression-Language/02-InspectRunnables.ipynb
=> [E-4] 13-LangChain-Expression-Language / 02-InspectRunnables.ipynb

02-Prompt/02-FewShotPromptTemplate.ipynb, 10-Retriever/06-MultiQueryRetriever.ipynb
🖥️ OS: Win
✅ Checklist
[V] Template: Tutorials follows the required template.
[YES] Table of Contents(TOC) Links: All Table of Contents links work. ((Yes/No)
[V] Image: Image filenames follow guidelines.
[V] *Imports: All import statements use the latest versions. Ensure "langchain-teddynote" is not used.
[V] Code Execution: Code runs without errors.
Comments:
폴더명 02-PROMPT => 02-Prompt
! => %
Chroma => Chroma
OpenAIEmbeddings = > OpenAIEmbeddings
=> [E-1] 02-Prompt / 02-FewShotPromptTemplate.ipynb

05-Memory/06-ConversationSummaryMemory.ipynb
Issue #202 수정사항 반영
```markdown
```
=> [E-4] 05-Memory / 06-ConversationSummaryMemory

04-Model/01-Models.ipynb
- [v] **PR Title Format**: I have confirmed that the PR title follows the correct format. _(e.g., [N-2] 07-Text Splitter / 07-RecursiveCharacterTextSplitter)_
- [v] **Committed Files**: I have ensured that no unnecessary files _(e.g., .bin, .gitignore, poetry.lock, pyproject.toml)_ are included. These files are not allowed.
- [v] **(Optional) Related Issue**: If this PR is linked to an issue, I have referenced the issue number in the PR message. _(e.g., Fixes #123)_
```markdown
- [v] **Template**: Tutorials follows the …
```
=> [E-3] 04-MODEL / 01-Models

13-LangChain-Expression-Language/12-RunnableRetry.ipynb
신규 3팀 RunnableRetry Draft Code입니다.
다음과 같은 사항 피드백 해주시면 감사하겠습니다.
- 기본 규칙 준수
- 추가 개발 필요한 사항
```markdown
```
=> [N-3] 13-LangChain-Expression-Language / 12-RunnableRetry

06-DocumentLoader/10-ArxivLoader.ipynb
```markdown
```
- https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/199 이슈 해결
=> [N-1] 06-DocumentLoader / 10-ArxivLoader 

05-Memory/08-LCEL-add-memory.ipynb
번역 / 검수 팀 @ee-juni 님께서 올려주신 이슈 수정하여 반영하였습니다!
노고에 감사드립니다 (_ _)
```markdown
```
=> [N-1] 05-Memory / 08-LCEL-add-memory

docs/03-OutputParser/02-CommaSeparatedListOutputParser.md
Gitbook 의 오타를 Quick fix 수정합니다.
=> [Gitbook] Quick Fix 

13-LangChain-Expression-Language/14-StreamRunnables.ipynb
[Title] StreamRunnables
[Language] ENG
[Packages] langchain_openai, langchain_anthropic, langchain, faiss
Added 14-StreamRunnables notebook
=> [N-3] 13-LCEL / 14-StreamRunnables

05-Memory/05-ConversationKGMemory.ipynb
docs : update for issue - "Proofread: < 05-Memory / 05-ConversationKGMemory >" #198
참고로 주셨던 링크 내용에서 아래 부분만 변경해 적용했습니다! 
Let's examine the memory after having a conversation using custom **a** `ConversationChain` with `ConversationKGMemory` by LCEL 
->
Let's examine the memory after having a conversation using **a** custom `ConversationChain` with `ConversationKGMemory` by LCEL
```markdown
```
If no one reviews your PR within a few days, please @-mention one of teddylee777, musangk, …
=> [E-4] 05-MEMORY/05-ConversationKGMemory

06-DocumentLoader/13-HWPLoader.ipynb
=> [N-1] 06-DocumentLoader / 13-HWPLoader

docs/README.md
[GitBook] Update: Uploaded README.md file
채윤님이 반영한 README.md 파일로 업로드합니다.
머지는 강제로 진행하겠습니다.
=> [GitBook] Update: Uploaded README.md file

11-Reranker/03-JinaReranker.ipynb
=> [E-2]11-Reranker/03-JinaReranker

06-DocumentLoader/07-PowerPointLoader.ipynb
#323 issue에 남겨주신 내용 검토 후 반영 완료하였습니다. 
꼼꼼히 리뷰해주셔서 정말 감사합니다!
```markdown
```
=> [N-1] 06-DocumentLoader / 07-PowerPointLoader

05-Memory/07-VectorStoreRetrieverMemory.ipynb
issue에 남겨주셨던 commit 내용을 반영하였습니다. 좋은 리뷰 감사드립니다 ☺️
FYI) 추가적으로 디스코드에서 언급된 내용을 반영하였습니다:
`load_dotenv(override=True)` 
```markdown
```
=> [E-4] 05-Memory / 07-VectorStoreRetrieverMemory

01-Basic/04-LangSmith-Tracking-Setup.ipynb
=> [E-1] 01-Basic / 04-LangSmith-Tracking-Setup

16-Evaluations/myrag.py
[Team] 16-evaluations
[Title] add the files
[Language] ENG
[files]  myrag.py, Newwhitepaper_Agents2.pdf
```markdown
```
=> [E16] 16-Evaluations / add the files

13-LangChain-Expression-Language/07-ChainDecorator.ipynb
Fixes #328
```markdown
```
꼼꼼한 검수 및 번역 교정 감사드립니다!
전달주신 링크 참고하여 아래 내용 수정하였습니다. 확인 부탁드립니다 감사합니다!
- 헤딩 @기호 제거 -> Creating Runnable objects with chain decorator
- RunnableLambda에 대해서만 다루는 튜토리얼이 존재하여 chain decorator에 대한 튜토리얼임을 표현하고 싶었습니다.
- Environment Setup 최신 템플릿 내용으로 변경
- https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/pull/295
- References 추가
- Table of Contents 순서 재배치 및 …
=> [E-4] 13-LCEL / 07-ChainDecorator

08-Embedding/02-CacheBackedEmbeddings.ipynb
링크: https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/144
내용: 교정 검수에 따른 수정 사항 적용
- 빈셀 삭제
- 영문 교정 적용
- 모듈명에 백틱 적용
- 레퍼런스명 수정
=> 08-Embedding / 02-CacheBackedEmbeddings 

04-Model/04-ModelSerialization.ipynb
[Version] proofread
[Language] ENG
#325
1. `!pip` -> `%pip`
2. remove cell output
```markdown
```
=> 04-Model / 04-ModelSerialization

11-Reranker/01-CrossEncoderReranker.ipynb
의견주신것 처럼 환경 설정이 앞으로 나오는 것이 좋아 보입니다.
해당 내용 반영하였습니다.
```markdown
```
=> [E-2] 11-Reranker / 01-CrossEncoderReranker

10-Retriever/08-SelfQueryRetriever.ipynb
=> [E-1] 10-Retriever / 08-SelfQueryRetriever

15-Agent/04-Agent-More-LLMs.ipynb
=> [E-4] 15-Agent / Agent-More-LLMs

13-LangChain-Expression-Language/03-RunnableLambda.ipynb
[13-LCEL / 03-RunnableLamda #414
](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/414#event-15968607609) 위하여 해당 파일 PR 드립니다. 감사 합니다.
```markdown
```
=> [E-4] 13-LCEL / 03-RunnableLamda

15-Agent/11-React-Agent.ipynb
=> [E-4] 15-Agent / 11-React-Agent.ipynb

14-Chains/03-Structured-Output-Chain.ipynb
안녕하세요. 리뷰 부탁드리겠습니다.
랭체인노트에서 사용된 퀴즈 예제가 너무 한국적(?)이라서  Topic을  K-FOOD로 수정하였습니다.
```markdown
```
=> [E-1] 14-Chains / 03-StructuredOutputChain

19-Cookbook/01-SQL/02-SpeechToSQL.ipynb
git commit -m "[Team] 신규1팀 UseCase
[Title] 02-SpeechtoSQL.ipynb
[Version] 1.1
[Language] ENG
{Package] sounddevice, wavio, faster-whisper
```markdown
```
=> [N-1] 01-SQL / 02-SpeechToSQL

05-Memory/02-ConversationBufferWindowMemory.ipynb
PR for Proofreading Issue #433  
```markdown
🖥️ OS: /Mac
- Comments:     
```
=> [E-4] 05-Memory / 02-ConversationBufferWindowMemory

07-TextSplitter/03-TextSplittingMethods_.ipynb
1. 다른 파일 제목이 좋을 것 같습니다. 튜토리얼에서 `TokenTextSplitter`보다 더 많은 내용을 다루고 있는 좋은 점이 잘 드러나지 않고, 사실 `TokenTextSplitter` 세션에서는 설명이 전무하여 의아하게 느낄 수 있습니다.
2. KoNLPy는 한국어 데이터로 적용 필요합니다. [최초 컨트리뷰터의 PR] (https://github.com/langchain-ai/langchain/pull/16003)을 참조해주세요. 저희가 사용하는 한국어 튜토리얼은 랭체인의 How-to를 번역해 작성한 것으로 보입니다. 때문에 직역한 영어 표기보다 공식 가이드를 레퍼런싱하는 것이 나을 듯 하고 활용 데이터만 교체하면 될 듯 합니다.
3. NLTK의 대체 활용으로 spaCy가 소개된 만큼 튜토리얼 순서를 변경하면 좋겠습니다.
4. 소제목을 다르게 사용하는 것을 제안 드립니다. 번역 관점으로 판단하였을 때 `tiktoken`과 `tokentextsplitter`, `sentencetransformers`은 예시 사용인 것 같고 `NLTK`와 `spaCy`소개할 내용과 다른 것 같습니다. 제가 모델과 코드사용에 대해 아직 모르는 부분들이 많기 때문에 `hugging face` 부분도 번역가 관점으로 다음과 같이 수정 제시 드려봅니다.
- [Overview](#overview)
- [Environment Setup](#environment-setup)
- [Example Usage of Tiktoken](#example-usage-of-tiktoken)
- [Example Usage of …
=> [N-2] 07-TextSplitter/03-TokenTextSplitter

11-Reranker/04-FlashRank-Reranker.ipynb
=> [E-2] 11-Reranker / 04-FlashRank-Reranker

05-Memory/10-Conversation-With-History.ipynb
=> [E-4] 05-Memory / 10-Conversation-With-History

10-Retriever/06-MultiQueryRetriever.ipynb
이슈에 있는 문장 수정 사항들을 반영했습니다.
감사합니다.
```markdown
```
=> [E-1] 10-Retriever / 06-MultiQueryRetriever

15-Agent/02-Bind-Tools.ipynb
=> [E-4] 15-Agent / 02-Bind-Tools

13-LangChain-Expression-Language/05-RunnableParallel.ipynb
=> [E-4] 13-LCEL / 05-RunnableParallel

05-Memory/01-ConversationBufferMemory.ipynb
=> Proofread: < 05-Memory / 01-ConversationBufferMemory >

15-Agent/03-Agent.ipynb
for resolve Proofread: < 15-Agent / 03-Agent > #473
꼼꼼한 리뷰 감사 합니다. 수정 내용 리뷰 부탁 드립니다.
수고 하십시오.
```markdown
🖥️ OS: Mac
- Comments:      
```
=> [E-4] 15-Agent / 03-Agent

13-LangChain-Expression-Language/11-Fallbacks.ipynb
=> [E-4] 13-LangChain-Expression-Language / 11-Fallbacks

12-RAG/01-RAG-Basic-PDF.ipynb
=> 12-RAG / 01-RAG-Basic-PDF revise

01-Basic/02-Getting-Started-Mac.ipynb
Remove unnecessary leading spaces from the image path
```markdown
```
@sooyoung-wind 수영님, 이미지 경로 앞 공백 제거 하였습니다. 확인 부탁드릴게요.
=> [E-1] 01-BASIC / 01-Follow the Installation Video_Mac

17-LangGraph/01-Core-Features/16-LangGraph-Errors.ipynb, 17-LangGraph/01-Core-Features/16-LangGraph-Erros.ipynb
=> [N-3] 17-LangGraph / 01-Core-Features / 16-LangGraph-Errors

13-LangChain-Expression-Language/09-Generator.ipynb
번역/검수팀 수정 내용 반영하였습니다. 너무 늦게 반영해서 죄송합니다!
https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/348
```markdown
```
=> [E-4]13-LCEL / 09-Generator

17-LangGraph/01-Core-Features/14-LangGraph-Subgraph-Transform-State.ipynb
=> [E-1] 17-LangGraph/01-CoreFeatures/14-LangGraph-Subgraph-Transform-State

17-LangGraph/02-Structures/rag/base.py, 17-LangGraph/02-Structures/rag/pdf.py, 17-LangGraph/02-Structures/rag/prompts/rag-prompt-with-chat-history.yaml, 17-LangGraph/02-Structures/rag/prompts/rag-prompt.yaml, 17-LangGraph/02-Structures/rag/utils.py, 17-LangGraph/03-Use-Cases/rag/base.py, 17-LangGraph/03-Use-Cases/rag/pdf.py, 17-LangGraph/03-Use-Cases/rag/prompts copy/rag-prompt-with-chat-history.yaml, 17-LangGraph/03-Use-Cases/rag/prompts copy/rag-prompt.yaml, 17-LangGraph/03-Use-Cases/rag/utils.py
LangGraph 실행을 위한 파일들 입니다. (@fastjw 님께서 제공해 주신 파일을 포함하고 있습니다)
명절이지만, 공통 파일로 코드 작성/리뷰가 필요한 상황인점 양해를 부탁 드립니다.
행복하고 건강한 명절 되십시오.
=> Upload files for LangGraph

17-LangGraph/01-Core-Features/15-LangGraph-Streaming-steps.ipynb
=> [E-2] 17-LangGraph / 01-Core-Features / 15-LangGraph-Streaming-steps

17-LangGraph/01-Core-Features/01-LangGraph-Introduction.ipynb
=> [E-1] 17-LangGraph / 01-Core-Features / 01-LangGraph-Introduction

17-LangGraph/01-Core-Features/10-LnagGraph-ToolNode.ipynb
[Issue No](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/571)
<업데이트 내용>
1. 안내 주신대로 Creating tools를 재설명하는 대신 Creating tools [깃북 링크](https://langchain-opentutorial.gitbook.io/langchain-opentutorial/15-agent/04-agent-more-llms)를 연결하였습니다.
2. 소제목 타이틀은 명사형으로 변경하였고, 공식 문서 [링크](https://langchain-ai.github.io/langgraph/how-tos/tool-calling/)를 참고하였습니다.
```markdown
```
=> [E-2] 17-LangGraph/01-Core-Features /10-LnagGraph-ToolNode

15-Agent/04-Agent-More-LLMs.ipynb
[Issue ticket ](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/560)
1. 수정해주신 [링크](https://github.com/chaeyoonyunakim/LangChain-OpenTutorial/commit/a2b4acec5277f375786a5c6fe5e466ead3c12189) 참고하여 대부분 수정하였습니다.
2. [Langchain docs](https://python.langchain.com/docs/how_to/custom_tools/)를 참고하여 기존 Define the tool 에서 Creating tools로 변경해봤는데 검토 부탁 드립니다.
3. Creating tools 섹션에서 함수 를 설명하는 부분은 가독성을 위해서 Args와 Return부분은 제거하여 보았습니다. 바로 밑줄에도 Args와 Returns가 설명되기 때문입니다.
위 2번, 3번을 제외하고 수정해주신 링크 참고하여 수정하였습니다.
링크에 수정 부분이 너무 많아서 죄송한 마음이 큽니다. 늦은시간까지 고생 해주셔서 감사 드리며,
추가 수정할 부분이 나오면 또 업데이트 부탁 드리겠습니다.
감사합니다.
```markdown
🖥️ OS: …
```
=> [E-4] 15-Agent / 04-Agent-More-LLMs

14-Chains/04-Structured-Data-Chat.ipynb
교정 파일 반영
```markdown
- Comments: {Write freely, 한국어 기술 가능}     교정팀의 수정사항이 반영됐습니다. 감사합니다.
```
=> [E-1] 14-Chains / 04-Structured-Data-Chat

14-Chains/02-SQL.ipynb
=> [E-1] 14-Chains / 02-SQL

10-Retriever/10-Kiwi-BM25-Retriever.ipynb
```markdown
```
@ee-juni @BokyungisaGod 님 #415  커밋 내역들 모두 확인했고, 수정돼있는 부분은 유지하고 수정 안돼있는 typo 수정 후 리뷰 부탁드립니다.
=> [E-1] 10-Retriever / 10-Kiwi-BM25-Retriever #415

10-Retriever/07-MultiVectorRetriever.ipynb
update proofread
```markdown
```
=> [E-1] 10-Retriever / 07-MultiVectorRetriever

09-VectorStore/utils/vectordbinterface.py
=> [N-2] 09-VectorStore / utils DocumentManagerInterface.py

06-DocumentLoader/02-PDFLoader.ipynb
- fix formatting (backtick 추가/제거)
```markdown
```
=> [N-1] 06-DocumentLoader / 02-PDFLoader

10-Retriever/11-Convex-Combination-Ensemble-Retriever.ipynb
https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/pull/476 를 오픈했었지만 이슈가 있었어서 다시 오픈합니다. 양해해주셔서 감사드립니다 ☺️
```markdown
```
=> [E-1] 10-Retriever / 11-Convex-Combination-Ensemble-Retriever

19-Cookbook/07-Agent/14-MoARAG.ipynb
처음 컨셉을 잡을 때, 여러 방면으로 고민을 하다가 Genspark의 MoA 기능을 구현해보았습니다. 주어진 사용자의 쿼리를 Multi query로 확장하고, 이를 여러 모델이 각각 검색 결과에 기반해 답변을 만든 뒤, 마지막에 이를 모두 종합하여 답변을 내는 방식입니다. 일단은 이 방식으로 더 고도화해나갈 예정입니다.
시간이 되면 MoA RAG - 문서 기반의 MoA 기능을 따로 추가해도 좋을 것 같습니다.
```markdown
```
=> [N-1] 07-Agent / 14-MoARAG

01-Basic/01-Getting-Started-Windows.ipynb
> 이슈발생에 따른 변경사항 반영 
1. 튜토리얼링크 및 vscode링크 보이지 않도록 변경  [명칭](주소)
2. ```powershell ``` 은 윈도우파워쉘 코드 특성 상 유지
```markdown
```
=> [E-1] 01-Basic / 01-Getting-Started-Windows.ipynb

20-Prompt/Prompting-Techniques-CoT-ToT-GoT.md, 20-Prompt/analyze-merged-docs.yaml, 20-Prompt/merge-docs.yaml, 20-Prompt/supervisor.yaml, 20-Prompt/tree-of-thoughts-game-15.yaml
[Title] Prompting Techniques
[Language] ENG
[Packages]
```markdown
```
=> [E-1] 20-Prompt / Prompting-Techniques-CoT-ToT-GoT

20-Prompt/advanced_relevance_evaluator.md, 20-Prompt/professional_grading_bot.md, 20-Prompt/relevance_evaluator.md
=> [E-1] 20-Prompt/evaluator_prompt

01-Basic/04-LangSmith-Tracking-Setup.ipynb
- [ x ] **PR Title Format**: I have confirmed that the PR title follows the correct format. _(e.g., [N-2] 07-Text Splitter / 07-RecursiveCharacterTextSplitter)_
- [ x ] **Committed Files**: I have ensured that no unnecessary files _(e.g., .bin, .gitignore, poetry.lock, pyproject.toml)_ are included. These files are not allowed.
- [ x ] **(Optional) Related Issue**: If this PR is linked to an issue, I have referenced the issue number in the PR message. _(e.g., Fixes #123)_
```markdown
- Comments: {Write freely, 한국어 기술 가능} …
```
=> [E-1]-01-Basic-/-04-LangSmith-Tracking-Setup #622

17-LangGraph/03-Use-Cases/16-LangGraph-Reflection.ipynb
=> [E-2] 17-LangGraph / 03-Use-Cases / 16-LangGraph-Reflection

04-Model/07-Huggingface-Endpoints.ipynb
update Proofread version
```markdown
```
=> [E-3] 04-Model / 07-Huggingface-Endpoints

17-LangGraph/03-Use-Cases/13-Tree-of-Thoughts.ipynb
기존 PR 을 닫고 새롭게 PR 진행했습니다.
다시 리뷰 부탁드립니다. 죄송합니다.
```markdown
```
=> [E-2] 17-LangGraph / 03-Use-Cases / 13-Tree-of-Thoughts.ipynb

17-LangGraph/03-Use-Cases/15-LangGraph-Functional-API.ipynb
=> [E-2] 17-LangGraph / 03-Use-Cases / 15-LangGraph-Functional-API

15-Agent/05-Iteration-HumanInTheLoop.ipynb
- [O ] **PR Title Format**: I have confirmed that the PR title follows the correct format. _(e.g., [N-2] 07-Text Splitter / 07-RecursiveCharacterTextSplitter)_
- [ O] **Committed Files**: I have ensured that no unnecessary files _(e.g., .bin, .gitignore, poetry.lock, pyproject.toml)_ are included. These files are not allowed.
[ https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/561#issuecomment-2642821387](url)
Content & Formatting Issues
Translation - Improvements needed in the translated versions.
항상 자세한 검수 감사드립니다.
1번은
바로 앞 노트북만 참조하기 보다는 전체적으로 앞선 내용을 써야할듯하여 아래 내용을 추가하였습니다.
In the previous tutorial, we leveraged LangChain's agent components:
Agent: The core component responsible for decision-making. …
=> [N-3] 15-Agent / 05-Iteration-HumanInTheLoop

03-OutputParser/02-CommaSeparatedListOutputParser.ipynb
2차 검수 이슈 #672 내용 수정하였습니다.
감사합니다.
```markdown
```
=> 03-OutputParser / 02-CommaSeparatedListOutputParser

16-Evaluations/04-LangSmith-Dataset.ipynb
=> 16-Evaluations / 04-LangSmith-Dataset 

17-LangGraph/02-Structures/05-LangGraph-Add-Query-Rewrite.ipynb
검수결과 반영하여 커밋한 내용에 대해 리뷰어 approve 하였으나,
다른 파일과 물려있어 분리하고 다시 PR
```markdown
```
=> 17-LangGraph / 02-Structures / 05-LangGraph-Add-Query-Rewrite.ipynb

20-Prompt/SummarizationPrompt.md
안녕하세요. 기존 PR이 닫혀버려서 신규로 PR 드립니다.
수현님이 피드백 주셨던 출력 관련 내용 업데이트와 함께 예제 코드 보강하였으며, Final Checks 및  Key Requirements 섹션은 추가하였습니다. 
```markdown
```
=> [E-1] 20-Prompt / Summarization-Promp

15-Agent/06-Agentic-RAG.ipynb
코멘트로 언급했던 부분도 반영하여 PR 올립니다 :)
좋은 의견 감사드립니다!
```markdown
```
=> [E-4] 15-Agent / 06-Agentic-RAG

15-Agent/09-MakeReport-Using-RAG-Websearching-Imagegeneration-Agent.ipynb
꼼꼼한 검수 감사 드립니다.
검수내용 반영해서 PR 요청 드립니다.
감사합니다.
```markdown
```
=> 15-Agent / 09-MakeReport-Using-RAG-Websearching-Imagegeneration-Agent

15-Agent/07-CSV-Excel-Agent.ipynb
[Title] CSV/Excel Analysis Agent
[Version] revision
[Language] ENG
[Packages] langchain_experimental, langchain_openai, langchain_core.agents
fixed typo
=> [E-4] 15-Agent / 07-CSV-Excel-Agent

08-Embedding/03-HuggingFaceEmbeddings.ipynb
=> Proofread: 08-Embedding / 03-HuggingFaceEmbeddings

03-OutputParser/03-StructuredOutputParser.ipynb
안녕하세요,
https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/190 이슈에 대해 교정사항을 반영했습니다!
그 외 추가적으로
1. answer the users question as best as possible
→ answer the user's question as best as possible
1. `langchain-opentutorial` is a package that provides a set of easy-to-use environment setup, useful functions and utilities for tutorials.
→ `langchain-opentutorial` is a package that provides a set of easy-to-use environment setup along with useful functions and utilities for tutorials.
2. You can checkout the [`langchain-opentutorial`](https://github.com/LangChain-OpenTutorial/langchain-opentutorial-pypi) for more details.
→ You can check out the [`langchain-opentutorial`](https://github.com/LangChain-OpenTutorial/langchain-opentutorial-pypi) for more details.
=> [Proofread] 03 - Output Parsers / 03-StructuredOutputParser

15-Agent/08-Agent-with-Toolkits-File-Management.ipynb
제안주신 백틱 사용 관련 수정 반영했습니다. (백틱 대신 볼드체 강조를 사용했습니다!) #591
```markdown
```
=> [E-4] 15-Agent / 08-Agent-with-Toolkits-File-Management

02-Prompt/05-Prompt-Caching.ipynb
안녕하세요. 제안해주신 proofread 읽고 작성한 수정사항입니다.
[Proofread: 92 - Prompt / 05 - Prompt Caching #695](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/695#event-16326529257)
수정사항은 다음과 같습니다.
- Table of Contents (##) -> (#)로 수정
- backtick 전부 (`) -> (```)로 수정 및 backtick 달아야 하는 부분 수정
- 일부 형식 오류(대소문자) 수정
```markdown
```
=> Proofread: 02-Prompt / 05-Prompt-Caching

19-Cookbook/08-Serving/01-FastAPI-Serving.ipynb
늦게 남기게 되어 죄송합니다ㅜ
피드백 부탁드립니다!
```markdown
```
=> [E-3] 19-Cookbook / 08-Serving / 01-FastAPI-Serving

16-Evaluations/06-LangSmith-Embedding-Distance-Evaluation.ipynb
안녕하세요 @Q0211 님, 꼼꼼한 검수 감사합니다.
수정하신 내용 반영 및 깃북을 위한 백틱 변경처리 하였습니다.
좋은 하루 되세요! 수정사항 있으시면 discord를 통해 알려주시면 감사하겠습니다.
=> Proofread: 16-Evaluations / 06-LangSmith-Embedding-Distance-Evaluations

06-DocumentLoader/06-WordLoader.ipynb
=> Proofread: 06-DocumentLoader / 06-WordLoader 

06-DocumentLoader/03-WebBaseLoader.ipynb
- ** 처리 뒤에 빈칸 추가
- 용어 대신 함수명으로 대체
함수명으로 쓰는 것이 훨씬 적절한 것 같습니다! 검수 감사드립니다.
```markdown
```
=> [N-1] 06-DocumentLoader/03-WebBaseLoader

19-Cookbook/08-Serving/03-LangServe-Agent-API.ipynb
=> [E-3] 19-Cookbook / 08-Serving / 03-LangServe-Agent-API 

19-Cookbook/07-Agent/19-NewEmployeeOnboardingChatbot.ipynb
- 이슈 #733 에 대한 개선 사항입니다.
Fixes #733
```markdown
```
=> [proofread] 19-Cookbook/07-Agent/19-NewEmployeeOnboardingChatbot.ipynb

06-DocumentLoader/05-ExcelLoader.ipynb
=> Proofread: 06-DocumentLoader / 05-ExcelLoader

16-Evaluations/09-CompareEvaluation.ipynb
- fix typo
Environment Setup 내용은 가이드 템플릿 따라 동일하게 작성했었는데
수정 필요한 부분인지 한번만 더 검토 부탁드리겠습니다 감사합니다!
```markdown
```
=> Proofread:  16-Evaluations / 09-CompareEvaluation

20-Prompt/Prompt-using-footnote-format.md
검수팀 수정사항 반영
- 불릿 포인트 비어있는 부분 수정
- main에 merge 된 줄 알고 실수로 브랜치 지워서 기존 PR이 닫혔습니다 ㅠㅠ
- 다시 승인 부탁 드립니다..!
```markdown
```
=> [E-1] 20-Prompt/Prompt-using-footnote-foramt.md

12-RAG/06-Translation.ipynb
[Title] Translation
[Version] proofread fix
[Language] ENG
https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/745#event-16380879256
@hong-seongmin
검수하시느라 고생많으십니다. 
검수 내용 반영하였습니다.
=> [N-3] 12-RAG / 06-Translation

06-DocumentLoader/02-PDFLoader.ipynb
아래 내용 수정하였습니다 확인 부탁드립니다 감사합니다 :)
- 비어 있는 셀 삭제
- 라이브러리 링크 추가 (PyPDF, PyMuPDF, PDFMiner ...)
- PyPDF 관련 설명 > array -> list 타입으로 수정
- 모듈명 backtick 처리
```markdown
```
=> Proofread: 06-DocumentLoader / 02-PDFLoader

13-LangChain-Expression-Language/01-RunnablePassThrough.ipynb
=> Proofread: 13-LangChain-Expression-Language / 01-RunnablePassThrough

06-DocumentLoader/01-DocumentLoader.ipynb
1. async_generator 뒤에 한칸 띄우셧는데 지워야할것 같습니다.
- 이 외에 한 칸씩 띄워진 backtick 들도 수정하였습니다!
2. asynchronous iterator 의 iterator 는 Iterator타입을 의미하느거 같은데 맞다면 Iterator 로 변경 해야할것 같습니다
- 개념을 설명하는 용어로써 사용해서 수정하지 않았습니다!
```markdown
```
=> [N-1] 06-DocumentLoader / 01-DocumentLoader

09-VectorStore/09-Neo4j.ipynb
번역-검수 이슈사항 수정 반영하였습니다.
```markdown
```
=> [N-2] 09-VectorStore / 09-Neo4j

19-Cookbook/07-Agent/20-LangGraphStudio-MultiAgent.ipynb
```markdown
```
@Q0211 번역검수팀 요청에 의해 문법, 오타, 포맷 수정 진행했습니다~! 
@obov @johnny9210 번거로우시겠지만 확인 후 승인 부탁드립니다 ¨̮
=> [N-1] 07-Agent / 20-LangGraphStudio-MultiAgent 

16-Evaluations/12-LangSmith-Pairwise-Evaluation.ipynb
```markdown
```
[수영님 리뷰]
0 -> langchain-kr을 따른 것이라 문제 없을 것 같습니다.
1 -> 문장 수정 했습니다.
2 -> 보충 설명 추가했습니다.
3 -> UI가 바뀐거라 수정하지 않아도 될 것 같습니다.
=> Proofread: 16-Evaluations / 12-LangSmith-Pairwise-Evaluation

20-Prompt/RAG-Citation-Prompt.md
https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/768
에 따라 References 부분을 수정했습니다.
```markdown
```
=> [E-1] 20-Prompt / RAG-Citation-Prompt

15-Agent/10-TwoAgentDebateWithTools.ipynb
=> Proofread: 15-Agent / 10-TwoAgentDebateWithTools

13-LangChain-Expression-Language/10-Binding.ipynb
-  (Optional) Related Issue: If this PR is linked to an issue, I have referenced the issue number in the PR message. (e.g., Fixes https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/pull/123)
```markdown
```
리뷰하느라 고생하셨습니다. 가이드 내용 모두 반영하였습니다. ^^
=> [N-3] 13-LangChain-Expression-Language / 10-Binding

13-LangChain-Expression-Language/05-RunnableParallel.ipynb
오타, 백틱 띄어쓰기, 문법 수정하여 커밋했습니다.
시간되실 때 검토 부탁드립니다.
감사합니다!
```markdown
```
=> [E-4] 13-LangChain-Expression-Language / 05-RunnableParallel

17-LangGraph/02-Structures/01-LangGraph-Building-Graphs.ipynb
#796
피드백 감사합니다! 용어로 강조의 의미가 더 큰 것 같아서 볼드 처리하였습니다!
```markdown
```
=> Proofread: 17-LangGraph / 02-Structures / 01-LangGraph-Building-Graphs

16-Evaluations/07-LangSmith-Custom-LLM-Evaluation.ipynb
=> Proofread: 16-Evaluations / 07-LangSmith-Custom-LLM-Evaluation

05-Memory/06-ConversationSummaryMemory.ipynb
proofread #827
2차 검수사항 반영
백틱처리 변경  ` -> ```
```markdown
```
=> Proofread: [E-4] 05-Memory / 06-ConversationSummaryMemory

20-Prompt/relevance_evaluator.md
=> Proofread:  20-Prompt / relevance_evaluator

17-LangGraph/03-Use-Cases/12-LangGraph-Cloud.ipynb
[Issue](https://github.com/LangChain-OpenTutorial/LangChain-OpenTutorial/issues/740)
Proofreading
1. backtick -> bold
2. add comment to codes
3. proofread
```markdown
```
=> 17-LangGraph/03-Use-Cases/12-LangGraph-Cloud

13-LangChain-Expression-Language/08-RunnableWithMessageHistory.ipynb
docs : update for proofread: <13-LangChain-Expression-Language /08-RunnableWithMessageHistory.ipynb > #806
교정해주신 부분 모두 반영했습니다. 친절한 설명 감사합니다 :)
```markdown
```
=> [E-4] 13-LangChain-Expression-Language /08-RunnableWithMessageHistory

12-RAG/10-Multi_modal_RAG-GPT-4o.ipynb
=> [E-1] 12-RAG / 10-Multi_modal_RAG-GPT-4o

01-Basic/07-LCEL-Interface.ipynb
- [ x ] **PR Title Format**: I have confirmed that the PR title follows the correct format. _(e.g., [N-2] 07-Text Splitter / 07-RecursiveCharacterTextSplitter)_
- [ x ] **Committed Files**: I have ensured that no unnecessary files _(e.g., .bin, .gitignore, poetry.lock, pyproject.toml)_ are included. These files are not allowed.
- [ x ] **(Optional) Related Issue**: If this PR is linked to an issue, I have referenced the issue number in the PR message. _(e.g., Fixes #123)_
```markdown
- Comments: {Write freely, 한국어 기술 가능} …
```
=> [E-1]-01-Basic-/-07-LCEL-Interface #623

README.md
Core Contributor 추가
```markdown
```
=> Update README.md with core contributor table

14-Chains/02-SQL.ipynb
Issue #871 볼드처리(** **) 공백 추가
```markdown
```
=> Proofread:<14-Chains/02-SQL>

10-Retriever/06-MultiQueryRetriever.ipynb
- [] **(Optional) Related Issue**: If this PR is linked to an issue, I have referenced the issue number in the PR message. _(e.g., Fixes #123)_
```markdown
```
=> Proofread:10-Retriever/06-MultiQueryRetriever

19-Cookbook/07-Agent/15-CoT-basedSmartWebSearch.ipynb
```markdown
```
---
#846 에 대한 수정사항:
- line 422
- 변경 내용: 설명 글에서는 **plan steps node** 보다는 `plan_steps_node` function 이 어떨지 의견 드립니다.
=> 고민 후 원상태로 두는게 낫다는 의견입니다.
- line 610
- 변경 내용: `fast_model` (or `smart_model`) → bold 처리 보다는 backtick 처리가 어떨까 싶습니다.
=> 반영했습니다! **fast_model** -> `fast_model`, **smart_model** -> `smart_model`
고생 많으십니다! 항상 감사드립니다.
=> Proofread: < 19-Cookbook / 07-Agent / 15-CoT-basedSmartWebSearch >

09-VectorStore/02-Chroma.ipynb, 09-VectorStore/utils/chroma/crud.py
```markdown
```
- HotFix : 요청하신 Delete Count 추가 했습니다.
=> [N-2] 09-VectorStore / 02-Chroma

17-LangGraph/01-Basic-LangGraph-Chatbot.ipynb
```markdown
```
@teddylee777 
Building Chatbot Using LangGraph and Groq API
=> [E-1] 17-LangGraph/01-Basic-LangGraph-Chatbot.ipynb 

07-TextSplitter/05-CodeSplitter.ipynb
```markdown
```
[N-2] 07-TextSplitter / 05-CodeSplitter
Proofread: < 07-TextSplitter / 05-CodeSplitter > - 2차 검수 #716
=> [N-2] 07-TextSplitter / 05-CodeSplitter
